#!/bin/sh

i=0
while read line
do
  line=${line##*/}
  array[ $i ]=${line%.png}
  (( i++ ))
done < <(ls png20/*.png)

for i in ${array[@]};
do
  convert transparent-40x40.png png20/$i.png -gravity center -compose over -composite png40/$i.png
done
