#!/usr/bin/sh

i=0
while read line
do
  line=${line##*/}
  array[ $i ]=${line%.svg}
  (( i++ ))
done < <(ls svg/*.svg)

for i in ${array[@]};
do
  inkscape -o png20/$i.png --export-type=png -w 20 -h 20 svg/$i.svg
done
