#!/bin/sh

i=0
while read line
do
  line=${line##*/}
  array[ $i ]=${line%.png}
  (( i++ ))
done < <(ls png40/*.png)

for i in ${array[@]};
do
  convert png40/$i.png -channel RGB -negate invert/$i.png
done
