#!/usr/bin/python

import sys
for i in sys.stdin.readlines():
  line = i.strip()
  if (line.startswith("% ")):
    pass
  elif (line == ""):
    pass
  elif (line == "\n"):
    pass
  else:
    print line
