#!/bin/sh

###################################
#####         SYSTEM         ######
###################################

# Background and Border Colors
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

# Keyboard Repeat Rate
riverctl set-repeat 50 300

# Exit riverctl
riverctl map normal Super+Shift Q exit

###################################
#####        WINDOWS         ######
###################################

# Close Focused View
riverctl map normal Super+Alt C close

# Bump View to Top of Layout Stack
riverctl map normal Super M zoom

# Focus Next/Previous View in Layout Stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Swap Focused View with Next/Previous View
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Toggle Fullscreen
riverctl map normal Super F toggle-fullscreen

# Toggle Float
riverctl map normal Super O toggle-float

# Resize/Move Views
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Change Layout Orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

###################################
#####          TAGS          ######
###################################

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

###################################
#####          APPS          ######
###################################

# Keybinds
riverctl map normal Super Return spawn alacritty

# Floating by Default


# App-ID Client Side Decorations


# Autostart

###################################
#####          SPAWN         ######
###################################
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6
