#!/bin/sh
bspc rule -r "*"

###---Autostart---###
xrdb ~/.Xresources &
compton -b &
# feh --bg-scale --no-fehbf ~/.config/wall.png &
sxhkd &
fcitx -d &
Thunderbird &

###---Monitors---###
bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9 10

###---Floating Apps---###
bspc rule -a Gimp desktop=^3 follow=on state=floating

###---Global Settings---###
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true

bspc config normal_border_color	"4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 9

###---Rules---###
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a Rambox desktop=^2 
bspc rule -a discord desktop=^4
bspc rule -a lutris desktop=^6
bspc rule -a steam desktop=^6
bspc rule -a minigalaxy desktop=^6
bspc rule -a Darktable desktop=^3 state=fullscreen
bspc rule -a Thunderbird desktop=^1
bspc rule -a zoom desktop=^5
