%%% file expl-array-index.mp
%%% Copyright 2009, 2011 Stephan Hennig
%
% This work may be distributed and/or modified under the conditions of
% the LaTeX Project Public License, either version 1.3 of this license
% or (at your option) any later version.  The latest version of this
% license is in http://www.latex-project.org/lppl.txt
%
input mpcolornames
for i=1 upto 4:
  show VioletRed[i];
endfor
end
